### ISSUE TITLE
Change the validator and utils codebase structure.

### ISSUE THREAD

**Issue by synchronizing** [Waultics/CryptoBook#22]
I believe that a new codebase style should be in order. As of right now, the following is occurring:
```
API -> Validator (function return) -> API -> Utils (function return) -> API (function return) -> Client
```
I believe perhaps a better format would be:
```
API -> Validator (calls) -> Utils (function return) -> Validator (function return) -> API (function return) -> Client
```
This is due to the fact some errors might be thrown by the `utils.py` file that I don't know if it would be worth catching it inside `utils`. Stuff such as `max tries has been reached`, `DDOS protection`, etc. This way utils is responsible solely to pulling data, and the verifier is the middle-man between the API and the pulling of data with `try` block ready to pick-up _specific_ exceptions (`ccxt.ddos.exception`, `ccxt.maxtries.exception`) and the validator would be ready to return to the API either the data or error. 

Discussion originally on #16 .

**Comment by Alescontrela** [comment]
I agree that the latter is a much better choice. I enjoy how simple api.py is, because I can quickly reference it to understand how I should format calls without having to dive through a ton of code. Now, when it comes to handling errors, why not just throw any error you're given directly at the client instead of catching individual errors? 

i.e.

```python
try utils.blah(request):
    # //...
except ccxt.ddos.exception as e:
   print(e)
except ccxt.maxtries.exception as e:
   print(e)
```

vs.

```python
try utils.blah(request):
    #//...
except e:
    print(e)
```

**Comment by synchronizing** [comment]
> I agree that the latter is a much better choice. I enjoy how simple api.py is, because I can quickly reference it to understand how I should format calls without having to dive through a ton of code. Now, when it comes to handling errors, why not just throw any error you're given directly at the client instead of catching individual errors?
> 
> i.e.
> 
> ```python
> try utils.blah(request):
>     # //...
> except ccxt.ddos.exception as e:
>    print(e)
> except ccxt.maxtries.exception as e:
>    print(e)
> ```
> 
> vs.
> 
> ```python
> try utils.blah(request):
>     #//...
> except e:
>     print(e)
> ```

Yes, I agree -- for most cases generalizing would be most useful. In some instances, however, catching specific errors would ensure we return back to the user the specific error that the server occurred. We don't have to catch every single one, but DDOS, for example, is best to reply with "max tries reached for {exchange}", rather than "server error." Does that make sense?

**Comment by synchronizing** [comment]
Improved with #30 .
