### ISSUE TITLE
Break CryptoBook/CryptoBook into CryptoBook-py and CryptoBook-js

### ISSUE THREAD

**Issue by Alescontrela** [Waultics/CryptoBook#24]
The only language currently implemented in the codebase is Python. This holds for both the api as well as the api implementation. However, after #15 gets merged in, there will be added javascript logic to the codebase (for ease of websocket implementations). To keep the codebase clean and organized, we should splot `CryptoBook/CryptoBook` into python and javascript directories and define additional docker-compose files in the respective directories.

**Comment by synchronizing** [comment]
#15 takes care of this. Good stuff.
